export enum ActionTypes {
  LOGIN_USER = 'LOGIN_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  READ_ACTIVITIES = 'READ_ACTIVITIES',
  CREATE_ACTIVITY = 'CREATE_ACTIVITY',
  UPDATE_ACTIVITY = 'UPDATE_ACTIVITY',
  DELETE_ACTIVITY = 'DELETE_ACTIVITY',
}
