import type { NextPage } from 'next';
import React from 'react';
import Head from 'next/head';
import { useSelector, useDispatch } from 'react-redux';
import Link from 'next/link';
import { actionCreators, State } from '../state';
import styles from '../styles/Home.module.css';
import { bindActionCreators } from 'redux';
import UserCard from '../components/UserCard';
import Activiries from '../components/Activities';
import axios from 'axios';
type User = {
  name: string | null;
};
const Home = () => {
  const dispatch = useDispatch();
  const { loginUser, logoutUser } = bindActionCreators(
    actionCreators,
    dispatch
  );
  const userState = useSelector((state: State) => state.user);
  const [user, setUser] = React.useState<User['name']>(null);
  // React.useEffect(() => {
  //   const userData = localStorage.getItem('user');
  //   if (!userData) {
  //     logoutUser();
  //   } else {
  //     const name = userData && JSON.parse(userData).user.name;
  //     loginUser(name);
  //     setUser(userState.user);
  //   }
  // }, [userState.user]);
  const [loading, setLoading] = React.useState(true);
  return (
    <main className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className={styles.main__section}>
        <UserCard />
        <Activiries />
      </section>
    </main>
  );
};

export default Home;
